dashboards/urls.py
from django.urls import path
from dashboards.views import (
    dashboard_view,
    summary_view,
    tmall_china_view,
    tmall_global_view,
    douyin_china_view,
    douyin_global_view
)

app_name = 'dashboards'

urlpatterns = [
    path('',view =dashboard_view,name="dashboard"),
    path('summary',view =summary_view,name="summary"),
    path('tmallchina',view =tmall_china_view,name="tmallchina"),
    path('tmallglobal',view =tmall_global_view,name="tmallglobal"),
    path('douyinchina',view =douyin_china_view,name="douyinchina"),
    path('douyinglobal',view =douyin_global_view,name="douyinglobal"),
   
]

pages/urls.py
from django.urls import path
from pages.views import (
authentication_signin_basic,
authentication_signin_cover,
authentication_signup_basic,
authentication_signup_cover,
authentication_pass_reset_basic,
authentication_pass_reset_cover,
authentication_lockscreen_basic,
authentication_lockscreen_cover,
authentication_logout_basic,
authentication_logout_cover,
authentication_success_msg_basic,
authentication_success_msg_cover,
authentication_twostep_basic,
authentication_twostep_cover,
authentication_404_basic,
authentication_404_cover,
authentication_404_alt,
authentication_500,
authentication_pass_change_basic,
authentication_pass_change_cover,
authentication_offline,
pages_starter,
pages_maintenance,
pages_coming_soon

)

app_name = "pages"

urlpatterns = [
    # Authentication
    path("authentication/signin-basic",view =authentication_signin_basic,name="authentication.signin_basic"),
    path("authentication/signin-cover",view =authentication_signin_cover,name="authentication.signin_cover"),
    path("authentication/signup-basic",view =authentication_signup_basic,name="authentication.signup_basic"),
    path("authentication/signup-cover",view =authentication_signup_cover,name="authentication.signup_cover"),
    path("authentication/password-reset-basic",view =authentication_pass_reset_basic,name="authentication.pass_reset_basic"),
    path("authentication/password-reset-cover",view =authentication_pass_reset_cover,name="authentication.pass_reset_cover"),
    path("authentication/lockscreen-basic",view =authentication_lockscreen_basic,name="authentication.lockscreen_basic"),
    path("authentication/lockscreen-cover",view =authentication_lockscreen_cover,name="authentication.lockscreen_cover"),
    path("authentication/logout-basic",view =authentication_logout_basic,name="authentication.logout_basic"),
    path("authentication/logout-cover",view =authentication_logout_cover,name="authentication.logout_cover"),
    path("authentication/success-msg-basic",view =authentication_success_msg_basic,name="authentication.success_msg_basic"),
    path("authentication/success-msg-cover",view =authentication_success_msg_cover,name="authentication.success_msg_cover"),
    path("authentication/two-step-authentication-basic",view =authentication_twostep_basic,name="authentication.twostep_basic"),
    path("authentication/two-step-authentication-cover",view =authentication_twostep_cover,name="authentication.twostep_cover"),
    path("authentication/404-basic",view =authentication_404_basic,name="authentication.404_basic"),
    path("authentication/404-cover",view =authentication_404_cover,name="authentication.404_cover"),
    path("authentication/404-alt",view =authentication_404_alt,name="authentication.404_alt"),
    path("authentication/500",view =authentication_500,name="authentication.500"),
    path("authentication/pass-change-basic",view =authentication_pass_change_basic,name="authentication.pass_change_basic"),
    path("authentication/pass-change-cover",view =authentication_pass_change_cover,name="authentication.pass_change_cover"),
    path("authentication/offline",view =authentication_offline,name="authentication.offline"),
    
    # Pages
    path("pages/starter-page",view =pages_starter,name="pages.starter"),
    path("pages/maintenance",view =pages_maintenance,name="pages.maintenance"),
    path("pages/coming-soon",view =pages_coming_soon,name="pages.coming_soon"),
] 

velzon/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.contrib.auth.decorators import login_required
from .views import MyPasswordChangeView, MyPasswordSetView
urlpatterns = [
    path('admin/', admin.site.urls),
    # Dashboard
    path('',include('dashboards.urls')),
    # Mscreening
    path('mscreening/',include('mscreening.urls')), 
    # keywordprod
    path('keywordprod/',include('keywordprod.urls')), 
    # Layouts
    path('layouts/',include('layouts.urls')),    
    # Pages
    path('pages/',include('pages.urls')),
    #account
    path(
        "account/password/change/",
        login_required(MyPasswordChangeView.as_view()),
        name="account_change_password",
    ),
    path(
        "account/password/set/",
        login_required(MyPasswordSetView.as_view()),
        name="account_set_password",
    ),
    # All Auth 
    path('account/', include('allauth.urls')),
    path('social-auth/',include('social_django.urls', namespace='social')),

    # file upload
    re_path(r'^fp/', include('django_drf_filepond.urls')),
]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" {% block html %} data-layout="horizontal" data-preloader="enabled" data-topbar="light" data-sidebar-size="lg" data-sidebar-image="none" {% endblock html %}>

  <head>
    <meta charset="utf-8"/>
    <title>
      {% block title %}{% endblock title %}
      | Velzon - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description"/>
    <meta content="Themesbrand" name="author"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

    {% block css %}
      {% block extra_css %}{% endblock extra_css %}

      <!-- gridjs css -->
      <link rel="stylesheet" href="{% static 'libs/gridjs/theme/mermaid.min.css' %}">
      <!-- Layout config Js -->
      <script src="{% static 'js/layout.js'%}"></script>
      <!-- Bootstrap Css -->
      <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css"/>
      <!-- Icons Css -->
      <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css"/>

      <!-- Tippy Css -->
      <link href="{% static 'libs/tippy.js/tippy.css'%}" id="tippy-style" rel="stylesheet" type="text/css"/>

      <!-- jsvectormap css -->
      <link href="{% static 'libs/jsvectormap/css/jsvectormap.min.css'%}" rel="stylesheet" type="text/css"/>

      <!--Swiper slider css-->
      <link href="{% static 'libs/swiper/swiper-bundle.min.css'%}" rel="stylesheet" type="text/css"/>

      <!-- dropzone css -->
      <link rel="stylesheet" href="{% static 'libs/dropzone/dropzone.css'%}" type="text/css"/>

      <!-- Filepond css -->
      <link rel="stylesheet" href="{% static 'libs/filepond/filepond.min.css'%}" type="text/css"/>
      <link rel="stylesheet" href="{% static 'libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.css'%}">

      <!-- App Css-->
      <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css"/>
      <!-- custom Css-->
      <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css"/>

    {% endblock css %}
  </head>

  <body>
    <div id="layout-loading"></div>
    <!-- Begin page -->
    <div id="layout-wrapper">
      {% block header %}
        {% include "partials/topbar.html" %}
      {% endblock header %}
      {% block sidebar %}
        {% include "partials/sidebar.html" %}
      {% endblock sidebar %}
      {% block content %}
        {% block pagetitle %}{% endblock pagetitle %}
        {% block footer %}{% endblock footer %}
      {% endblock content %}
    </div>

    {% block extra_content %}{% endblock extra_content %}

    <!-- removeNotificationModal -->
    <div id="removeNotificationModal" class="modal fade zoomIn" tabindex="-1" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="NotificationModalbtn-close"></button>
          </div>
          <div class="modal-body">
            <div class="mt-2 text-center">
              <lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop" colors="primary:#f7b84b,secondary:#f06548" style="width:100px;height:100px"></lord-icon>
              <div class="mt-4 pt-2 fs-15 mx-4 mx-sm-5">
                <h4>Are you sure ?</h4>
                <p class="text-muted mx-4 mb-0">Are you sure you want to remove this Notification ?</p>
              </div>
            </div>
            <div class="d-flex gap-2 justify-content-center mt-4 mb-2">
              <button type="button" class="btn w-sm btn-light" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn w-sm btn-danger" id="delete-notification">Yes, Delete It!</button>
            </div>
          </div>

        </div>
        <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->

    <!--preloader-->
    <div id="preloader">
      <div id="status">
        <div class="spinner-border text-primary avatar-sm" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
    </div>

    <!-- END layout-wrapper -->
    {% block right_sidebar %}
      {% include "partials/customizer.html" %}
    {% endblock right_sidebar %}

    {% block javascript %}

      <script>
        function getChartColorsArray(e) {
          if (null !== document.getElementById(e)) {
            var t = document
              .getElementById(e)
              .getAttribute("data-colors");
            if (t) 
              return (t = JSON.parse(t)).map(function (e) {
                var t = e.replace(" ", "");
                return -1 === t.indexOf(",")
                  ? getComputedStyle(document.documentElement).getPropertyValue(t) || t
                  : 2 == (e = e.split(",")).length
                    ? "rgba(" + getComputedStyle(document.documentElement).getPropertyValue(e[0]) + "," + e[1] + ")"
                    : t;
              });
            console.warn("data-colors Attribute not found on:", e);
          }
        }

        const language = {
          'search': {
            'placeholder': '검색...'
          },
          sort: {
            sortAsc: '오름차순 정렬',
            sortDesc: '내림차순 정렬'
          },
          'pagination': {
            'previous': '이전',
            'next': '다음',
            of: '전체',
            to: '~',
            'showing': ' ',
            'results': () => '건'
          },
          loading: '조회중입니다...',
          noRecordsFound: '검색 결과가 없습니다.',
          error: '오류가 발생했습니다.'
        };
      </script>

      <!-- JAVASCRIPT -->
      <script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
      <script src="{% static 'libs/@popperjs/core/umd/popper.min.js'%}"></script>
      <script src="{% static 'libs/tippy.js/tippy.umd.min.js'%}"></script>
      <script src="{% static 'libs/simplebar/simplebar.min.js'%}"></script>
      <script src="{% static 'libs/node-waves/waves.min.js'%}"></script>
      <script src="{% static 'libs/feather-icons/feather.min.js'%}"></script>
      <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
      <script src="{% static 'js/plugins.js'%}"></script>

      <!-- echarts js -->
      <script src="{% static 'libs/echarts/echarts.min.js' %}"></script>

      <!-- apexcharts -->
      <script src=" {% static 'libs/apexcharts/apexcharts.min.js'%} "></script>

      <!-- Vector map-->
      <script src=" {% static 'libs/jsvectormap/js/jsvectormap.min.js'%}"></script>
      <script src="{% static 'libs/jsvectormap/maps/world-merc.js'%}"></script>

      <!-- dropzone min -->
      <script src="{% static 'libs/dropzone/dropzone-min.js'%}"></script>

      <!-- filepond js -->
      <script src="{% static 'libs/filepond/filepond.min.js'%}"></script>
      <script src="{% static 'libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.js'%}"></script>
      <script src="{% static 'libs/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min.js'%}"></script>
      <script src="{% static 'libs/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min.js'%}"></script>
      <script src="{% static 'libs/filepond-plugin-file-encode/filepond-plugin-file-encode.min.js'%}"></script>

      <!-- gridjs js -->
      <script src="{% static 'libs/gridjs/gridjs.umd.js' %}"></script>

      <!-- aos js -->
      <script src="{% static 'libs/aos/aos.js' %}"></script>
      <!-- prismjs plugin -->
      <script src="{% static 'libs/prismjs/prism.js' %}"></script>
      <!-- animation init -->
      <script src="{% static 'js/pages/animation-aos.init.js' %}"></script>

      {% block extra_js %}{% endblock extra_js %}

      <!-- App js -->
      <script src="{% static 'js/app.js'%}"></script>

    {% endblock javascript %}

  </body>

</html>

templates/partials/footer.html
{% block footer %}
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © Velzon.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
                                Design & Develop by Themesbrand
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
{% endblock footer %}
    

templates/partials/page-title.html
<!-- start page title -->
<div class="row">
  <div class="col-12">
    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
      <h4 class="mb-sm-0">{{title}}</h4>

      <div class="page-title-right">
        <ol class="breadcrumb m-0">
          <li class="breadcrumb-item active">
            <a href="/">
              <i class="las la-home"></i>
            </a>
          </li>
          {% if pagetitle %}
            <li class="breadcrumb-item">
              <a href="javascript: void(0);">{{pagetitle}}</a>
            </li>
          {% endif %}
          <li class="breadcrumb-item active">{{title}}</li>
        </ol>
      </div>

    </div>
  </div>
</div>
<!-- end page title -->

templates/partials/sidebar.html
{% load static %}
{% block sidebar %}
  <!-- ========== App Menu ========== -->
  <div class="app-menu navbar-menu">
    <!-- LOGO -->
    <div class="navbar-brand-box">
      <!-- Dark Logo-->
      <a href="{% url 'dashboards:dashboard'%}" class="logo logo-dark">
        <span class="logo-sm">
          <img src="{% static 'images/logo-sm.png'%}" alt="" height="22">
        </span>
        <span class="logo-lg">
          <img src="{% static 'images/logo-dark.png'%}" alt="" height="17">
        </span>
      </a>
      <!-- Light Logo-->
      <a href="{% url 'dashboards:dashboard'%}" class="logo logo-light">
        <span class="logo-sm">
          <img src="{% static 'images/logo-sm.png'%}" alt="" height="22">
        </span>
        <span class="logo-lg">
          <img src="{% static 'images/logo-light.png'%}" alt="" height="17">
        </span>
      </a>
      <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover" id="vertical-hover">
        <i class="ri-record-circle-line"></i>
      </button>
    </div>

    <div id="scrollbar">
      <div class="container-fluid">

        <div id="two-column-menu"></div>
        <ul class="navbar-nav" id="navbar-nav">
          <li class="menu-title">
            <span data-key="t-menu">Menu</span>
          </li>
          <li class="nav-item">
            <a class="nav-link menu-link" href="#sidebarDashboards" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarDashboards">
              <i class="bx bxs-dashboard"></i>
              <span>중국 매출대시보드</span>
              <!--data-key="t-dashboards"-->
            </a>
            <div class="collapse menu-dropdown" id="sidebarDashboards">
              <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                  <a href="{% url 'dashboards:summary' %}" class="nav-link" data-key="t-summary">
                    Summary
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'dashboards:tmallchina' %}" class="nav-link" data-key="t-tmall-china">
                    Tmall 내륙
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'dashboards:tmallglobal' %}" class="nav-link" data-key="t-tmall-global">
                    Tmall 글로벌
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'dashboards:douyinchina' %}" class="nav-link" data-key="t-douyin-china">
                    Douyin 내륙
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'dashboards:douyinglobal' %}" class="nav-link" data-key="t-douyin-global">
                    Douyin 글로벌
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link menu-link" href="#sidebarApps" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarApps">
              <i class="bx bxs-dashboard"></i>
              <span data-key="t-review">리뷰분석</span>
            </a>
            <div class="collapse menu-dropdown" id="sidebarApps">
              <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                  <a href="#" class="nav-link" data-key="t-summary">
                    Summary
                  </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link" data-key="t-tmall-china">
                    Tmall 내륙
                  </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link" data-key="t-tmall-global">
                    Tmall 글로벌
                  </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link" data-key="t-douyin-china">
                    Douyin 내륙
                  </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link" data-key="t-douyin-global">
                    Douyin 글로벌
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link menu-link" id="sidebarMscreening" href="/mscreening" role="button" aria-controls="sidebarMscreening">
              <i class="bx bx-book-open"></i>
              <span data-key="t-mscreening">위생허가 스크리닝</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link menu-link" id="sidebarKeywordprod" href="/keywordprod" role="button" aria-controls="sidebarKeywordprod">
              <i class="bx bx-book-open"></i>
              <span data-key="t-keyword">검색어기반 상품개발</span>
            </a>
          </li>
          <!-- end Dashboard Menu -->

        </ul>
      </div>
      <!-- Sidebar -->
    </div>
    <div class="sidebar-background"></div>
  </div>
  <!-- Left Sidebar End -->
  <!-- Vertical Overlay-->
  <div class="vertical-overlay"></div>
{% endblock sidebar %}

templates/partials/vendor-scripts.html
{% load static %}
<!-- JAVASCRIPT -->
<script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'libs/tippy.js/tippy.umd.min.js'%}"></script>
<script src="{% static 'libs/simplebar/simplebar.min.js'%}"></script>
<script src="{% static 'libs/node-waves/waves.min.js'%}"></script>
<script src="{% static 'libs/feather-icons/feather.min.js'%}"></script>
<script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
<script src="{% static 'js/plugins.js'%}"></script>